//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThLaunchSite.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThLaunchSite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Above Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppPrimaryAboveNormal {
            get {
                return ResourceManager.GetString("AppPrimaryAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppPrimaryBelowNormal {
            get {
                return ResourceManager.GetString("AppPrimaryBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppPrimaryHigh {
            get {
                return ResourceManager.GetString("AppPrimaryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppPrimaryIdle {
            get {
                return ResourceManager.GetString("AppPrimaryIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppPrimaryNormal {
            get {
                return ResourceManager.GetString("AppPrimaryNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExecute {
            get {
                return ResourceManager.GetString("ButtonExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonLaunchGame {
            get {
                return ResourceManager.GetString("ButtonLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register to Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRegisterToSettings {
            get {
                return ResourceManager.GetString("ButtonRegisterToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Resize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonResize {
            get {
                return ResourceManager.GetString("ButtonResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRestore {
            get {
                return ResourceManager.GetString("ButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Seach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Game▾ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSelectGame {
            get {
                return ResourceManager.GetString("ButtonSelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always on Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBoxAlwaysOnTop {
            get {
                return ResourceManager.GetString("CheckBoxAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back up score file when game ends に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBoxBackupScoreFileWhenGameEnd {
            get {
                return ResourceManager.GetString("CheckBoxBackupScoreFileWhenGameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Main Window Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBoxFixMainWindowSize {
            get {
                return ResourceManager.GetString("CheckBoxFixMainWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grant Administrator Privileges に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBoxGrantAdministratorPrivileges {
            get {
                return ResourceManager.GetString("CheckBoxGrantAdministratorPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as trial version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBoxSetAsTrial {
            get {
                return ResourceManager.GetString("CheckBoxSetAsTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnDescription {
            get {
                return ResourceManager.GetString("DataGridCulumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnDeveloper {
            get {
                return ResourceManager.GetString("DataGridCulumnDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnGameEndTime {
            get {
                return ResourceManager.GetString("DataGridCulumnGameEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnGameName {
            get {
                return ResourceManager.GetString("DataGridCulumnGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnGameRunningTime {
            get {
                return ResourceManager.GetString("DataGridCulumnGameRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnGameStartTime {
            get {
                return ResourceManager.GetString("DataGridCulumnGameStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnID {
            get {
                return ResourceManager.GetString("DataGridCulumnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnName {
            get {
                return ResourceManager.GetString("DataGridCulumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridCulumnVersion {
            get {
                return ResourceManager.GetString("DataGridCulumnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game capture files storage folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageCaptureFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageCaptureFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   custom.exe Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageCustomProgramNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageCustomProgramNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to change the game base primary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToChangeGameBasePrimary {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToChangeGameBasePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to configure application settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToConfigApplicationSettings {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToConfigApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create external tools configuration file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreateExternalToolsConfigFile {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreateExternalToolsConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to configure the games edition settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreateGameEditionConfigFile {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreateGameEditionConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to configure game path settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreateGamePathConfigFile {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreateGamePathConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create plugins folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreatePluginDirecoty {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreatePluginDirecoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create score file backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreateScoreBackup {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreateScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create configuration file storage directory. Exit the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToCreateSettingsDirectory {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToCreateSettingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToDeleteBackup {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to detect a game process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToDetectGameProcess {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToDetectGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   thprac.exe Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToFindThpracFiles {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToFindThpracFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save game execution history. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToGameExecutionLog {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToGameExecutionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to configure game execution history. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToGetGameExecutionLog {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToGetGameExecutionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get plugins. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToGetPlugins {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToGetPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   was failed to install に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToInstall {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to kill the game process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToKillGameProcess {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToKillGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read backup folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToReadBackupDirectory {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToReadBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the specified file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToReadSpecifiedFile {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToReadSpecifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read vpatch.ini. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToReadVpatchIni {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToReadVpatchIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to restore from backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToRestoreFromBackup {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToSaveFile {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToSaveSettings {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start the custom.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToStartCustomProgram {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToStartCustomProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start the game process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageFailedToStartGameProcess {
            get {
                return ResourceManager.GetString("ErrorMessageFailedToStartGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game executable files Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageGameFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageGameFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is invalid selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageInvalidSelection {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東方管制塔 NX (Touhou Control Tower NX) has already started. Multiple activations are not possible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageMultiActivation {
            get {
                return ResourceManager.GetString("ErrorMessageMultiActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vpatch.ini Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageNotFoundVpatchIni {
            get {
                return ResourceManager.GetString("ErrorMessageNotFoundVpatchIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageSpecifiedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageSpecifiedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Files Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCaptureFileFormat {
            get {
                return ResourceManager.GetString("LabelCaptureFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Game Base Primary: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelChangeGameBasePrimary {
            get {
                return ResourceManager.GetString("LabelChangeGameBasePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Capture Files Folder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelGameCaptureFolder {
            get {
                return ResourceManager.GetString("LabelGameCaptureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Executable Files List: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelGameFilesList {
            get {
                return ResourceManager.GetString("LabelGameFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Execution Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelGamePlayTime {
            get {
                return ResourceManager.GetString("LabelGamePlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHeight {
            get {
                return ResourceManager.GetString("LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation Target: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelInstallTarget {
            get {
                return ResourceManager.GetString("LabelInstallTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have been running Touhou for this long cumulatively に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelMessageTotalGameRunningTime {
            get {
                return ResourceManager.GetString("LabelMessageTotalGameRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelOption {
            get {
                return ResourceManager.GetString("LabelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelPath {
            get {
                return ResourceManager.GetString("LabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution Time by Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRunningTimeByGame {
            get {
                return ResourceManager.GetString("LabelRunningTimeByGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of Backups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelScoreBackupsList {
            get {
                return ResourceManager.GetString("LabelScoreBackupsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search _Root: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelSearchRootFolder {
            get {
                return ResourceManager.GetString("LabelSearchRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelToolName {
            get {
                return ResourceManager.GetString("LabelToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabControlPanel {
            get {
                return ResourceManager.GetString("MainTabControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Execution History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabGameHistory {
            get {
                return ResourceManager.GetString("MainTabGameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score Files Backups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabScoreBackup {
            get {
                return ResourceManager.GetString("MainTabScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabSettings {
            get {
                return ResourceManager.GetString("MainTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About DynamicAero2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAboutDynamicAero2 {
            get {
                return ResourceManager.GetString("MenuAboutDynamicAero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About This Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAboutThisTool {
            get {
                return ResourceManager.GetString("MenuAboutThisTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Game Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCaptureGameWindow {
            get {
                return ResourceManager.GetString("MenuCaptureGameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Catch Running Game Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCatchRunningGameProcess {
            get {
                return ResourceManager.GetString("MenuCatchRunningGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Games に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCreateAllGameScoreBackup {
            get {
                return ResourceManager.GetString("MenuCreateAllGameScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Score _Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCreateScoreBackup {
            get {
                return ResourceManager.GetString("MenuCreateScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuCreateSelectedGameScoreBackup {
            get {
                return ResourceManager.GetString("MenuCreateSelectedGameScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit vpatch.ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuEditVpatchIni {
            get {
                return ResourceManager.GetString("MenuEditVpatchIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuExitApplication {
            get {
                return ResourceManager.GetString("MenuExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xternal Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuExternalTools {
            get {
                return ResourceManager.GetString("MenuExternalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGame {
            get {
                return ResourceManager.GetString("MenuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Install Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuInstallTools {
            get {
                return ResourceManager.GetString("MenuInstallTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill Running Game Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuKillGameProcess {
            get {
                return ResourceManager.GetString("MenuKillGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch _custom.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLaunchCustomProgram {
            get {
                return ResourceManager.GetString("MenuLaunchCustomProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Launch Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLaunchGame {
            get {
                return ResourceManager.GetString("MenuLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game with Applying _Any Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLaunchGameWithAnyTool {
            get {
                return ResourceManager.GetString("MenuLaunchGameWithAnyTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game with Applying _thprac.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLaunchGameWithThprac {
            get {
                return ResourceManager.GetString("MenuLaunchGameWithThprac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game with Applying _vpatch.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLaunchGameWithVpatch {
            get {
                return ResourceManager.GetString("MenuLaunchGameWithVpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Tools _Manger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuManageExternalTools {
            get {
                return ResourceManager.GetString("MenuManageExternalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuNone {
            get {
                return ResourceManager.GetString("MenuNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Game Capture Files Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOpenCaptureFolder {
            get {
                return ResourceManager.GetString("MenuOpenCaptureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open Game Installation Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOpenGameDirectory {
            get {
                return ResourceManager.GetString("MenuOpenGameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open log.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOpenGameLog {
            get {
                return ResourceManager.GetString("MenuOpenGameLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Plugin Base Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPluginBaseVersion {
            get {
                return ResourceManager.GetString("MenuPluginBaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Plugin Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPluginManager {
            get {
                return ResourceManager.GetString("MenuPluginManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Game Executable Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSearchGameFile {
            get {
                return ResourceManager.GetString("MenuSearchGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send _Feedback に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSendFeedback {
            get {
                return ResourceManager.GetString("MenuSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Path Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSetGamePath {
            get {
                return ResourceManager.GetString("MenuSetGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSystemInformation {
            get {
                return ResourceManager.GetString("MenuSystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Cumulative Execution Time Statistics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTotalGameRunningStatistics {
            get {
                return ResourceManager.GetString("MenuTotalGameRunningStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   will be deleted. Is itOK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAskDelete {
            get {
                return ResourceManager.GetString("MessageAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting Game End Mode. Do you really want to close 東方管制塔? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAskGameExit {
            get {
                return ResourceManager.GetString("MessageAskGameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is it OK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAskIsItOk {
            get {
                return ResourceManager.GetString("MessageAskIsItOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   already exists in the installation destination folder. Do you want to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAskOverwriteTool {
            get {
                return ResourceManager.GetString("MessageAskOverwriteTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Creation Date: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBackupCreationDate {
            get {
                return ResourceManager.GetString("MessageBackupCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBackupFileName {
            get {
                return ResourceManager.GetString("MessageBackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   was canceled to install. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCanceledInstall {
            get {
                return ResourceManager.GetString("MessageCanceledInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game window capture was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCaptureCanceled {
            get {
                return ResourceManager.GetString("MessageCaptureCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreated {
            get {
                return ResourceManager.GetString("MessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has already been added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageExternalToolExists {
            get {
                return ResourceManager.GetString("MessageExternalToolExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   executable file was registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGamePathRegisterToSettings {
            get {
                return ResourceManager.GetString("MessageGamePathRegisterToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInstall {
            get {
                return ResourceManager.GetString("MessageInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop all the files you want to install に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInstallToolDescription1 {
            get {
                return ResourceManager.GetString("MessageInstallToolDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   into this window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInstallToolDescription2 {
            get {
                return ResourceManager.GetString("MessageInstallToolDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple thprac executables were found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageMultiThpracFilesFound {
            get {
                return ResourceManager.GetString("MessageMultiThpracFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [No Game Selected] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNoGameSelected {
            get {
                return ResourceManager.GetString("MessageNoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No installation destination is selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNoInstallTargetSelected {
            get {
                return ResourceManager.GetString("MessageNoInstallTargetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrited and installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOverwriteInstall {
            get {
                return ResourceManager.GetString("MessageOverwriteInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageRestore {
            get {
                return ResourceManager.GetString("MessageRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;s score file will be restored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageRestoreFromBackup {
            get {
                return ResourceManager.GetString("MessageRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSave {
            get {
                return ResourceManager.GetString("MessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score File Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageScoreFileNotFound {
            get {
                return ResourceManager.GetString("MessageScoreFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSearching {
            get {
                return ResourceManager.GetString("MessageSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search root folder Not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSearchRootFolderNotFound {
            get {
                return ResourceManager.GetString("MessageSearchRootFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the backup file to delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectBackupFileToDelete {
            get {
                return ResourceManager.GetString("MessageSelectBackupFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the backup file to restore from. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectBackupFileToRestoreFrom {
            get {
                return ResourceManager.GetString("MessageSelectBackupFileToRestoreFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the game you want to set a path for from the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectGameToSetPathFromList {
            get {
                return ResourceManager.GetString("MessageSelectGameToSetPathFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a path to register to settings from the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectPathFromGameFilesList {
            get {
                return ResourceManager.GetString("MessageSelectPathFromGameFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a thprac to apply. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectThpracFile {
            get {
                return ResourceManager.GetString("MessageSelectThpracFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a tool to apply. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectToolToApply {
            get {
                return ResourceManager.GetString("MessageSelectToolToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set search root folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSetSearchRootFolder {
            get {
                return ResourceManager.GetString("MessageSetSearchRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The game process was killed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageToKillGameProcess {
            get {
                return ResourceManager.GetString("MessageToKillGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the game path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageToSetGamePath {
            get {
                return ResourceManager.GetString("MessageToSetGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusAdministrator {
            get {
                return ResourceManager.GetString("StatusAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game is Running... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusGameRunnning {
            get {
                return ResourceManager.GetString("StatusGameRunnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusUser {
            get {
                return ResourceManager.GetString("StatusUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAllFile {
            get {
                return ResourceManager.GetString("TextAllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Disabled) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextDisabled {
            get {
                return ResourceManager.GetString("TextDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextExecutableFile {
            get {
                return ResourceManager.GetString("TextExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Input Monitor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextKeyInputMonitor {
            get {
                return ResourceManager.GetString("TextKeyInputMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugins: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPluginList {
            get {
                return ResourceManager.GetString("TextPluginList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Architecture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextProcessArchitecture {
            get {
                return ResourceManager.GetString("TextProcessArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Architecture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextSystemArchitecture {
            get {
                return ResourceManager.GetString("TextSystemArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Resizer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWindowResizer {
            get {
                return ResourceManager.GetString("TextWindowResizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeBlack {
            get {
                return ResourceManager.GetString("ThemeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WPF Standard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeWPFStandard {
            get {
                return ResourceManager.GetString("ThemeWPFStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About DynamicAero2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleAboutDynamicAero2 {
            get {
                return ResourceManager.GetString("TitleAboutDynamicAero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About This Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleAboutThisTool {
            get {
                return ResourceManager.GetString("TitleAboutThisTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add External Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleAddExternalTool {
            get {
                return ResourceManager.GetString("TitleAddExternalTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Game Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleCaptureGameWindow {
            get {
                return ResourceManager.GetString("TitleCaptureGameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Score Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleCreateScoreBackup {
            get {
                return ResourceManager.GetString("TitleCreateScoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleDeleteBackup {
            get {
                return ResourceManager.GetString("TitleDeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Tools Manger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleExternalToolsManager {
            get {
                return ResourceManager.GetString("TitleExternalToolsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleInstallTools {
            get {
                return ResourceManager.GetString("TitleInstallTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill Game Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleKillGameProcess {
            get {
                return ResourceManager.GetString("TitleKillGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Plugin Base Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitlePlugInBaseVersion {
            get {
                return ResourceManager.GetString("TitlePlugInBaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitlePluginManager {
            get {
                return ResourceManager.GetString("TitlePluginManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore from Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleRestoreFromBackup {
            get {
                return ResourceManager.GetString("TitleRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Game Executable Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSearchGameFile {
            get {
                return ResourceManager.GetString("TitleSearchGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select thprac に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSelectThprac {
            get {
                return ResourceManager.GetString("TitleSelectThprac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSelectTool {
            get {
                return ResourceManager.GetString("TitleSelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Path Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSetGamePath {
            get {
                return ResourceManager.GetString("TitleSetGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSystemInformation {
            get {
                return ResourceManager.GetString("TitleSystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select game capture files storage folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleToSetGameCaptureFolder {
            get {
                return ResourceManager.GetString("TitleToSetGameCaptureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Cumulative Execution Time Statistics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleTotalGameRunningStatistics {
            get {
                return ResourceManager.GetString("TitleTotalGameRunningStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vpatch.ini Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleVpatchIniEditor {
            get {
                return ResourceManager.GetString("TitleVpatchIniEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Game Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipCaptureGameWindow {
            get {
                return ResourceManager.GetString("ToolTipCaptureGameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit vpatch.ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipEditVpatchIni {
            get {
                return ResourceManager.GetString("ToolTipEditVpatchIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill Running Game Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipKillGameProcess {
            get {
                return ResourceManager.GetString("ToolTipKillGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch custom.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipLaunchCustomProgram {
            get {
                return ResourceManager.GetString("ToolTipLaunchCustomProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game with Applying thprac.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipLaunchGameWithThprac {
            get {
                return ResourceManager.GetString("ToolTipLaunchGameWithThprac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Game with Applying vpatch.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipLaunchGameWithVpatch {
            get {
                return ResourceManager.GetString("ToolTipLaunchGameWithVpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Game Installation Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipOpenGameFolder {
            get {
                return ResourceManager.GetString("ToolTipOpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open log.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipOpenGameLog {
            get {
                return ResourceManager.GetString("ToolTipOpenGameLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipPreset {
            get {
                return ResourceManager.GetString("ToolTipPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Game Executable Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipSearchGameFile {
            get {
                return ResourceManager.GetString("ToolTipSearchGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Path Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipSetGamePath {
            get {
                return ResourceManager.GetString("ToolTipSetGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipSystemInformation {
            get {
                return ResourceManager.GetString("ToolTipSystemInformation", resourceCulture);
            }
        }
    }
}
